GameFinder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Home page with index of user's game requests.
    path('', views.index, name='index'),
    # View details of a single event and modify/delete.
    path('details/<int:GameRequestID>/', views.details, name='details'),
    path('details/', views.details, name='new request'),
    # Form submission target.
    path('submit/<int:GameRequestID>', views.submit, name='submit'),
    # Delete the request a form is attached to.
    path('delete/<int:GameRequestID>', views.delete, name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}D&D Player Finder{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/details.html
{% extends "base.html" %}

{% block title %}Details{% endblock %}

{% block content %}
  <h2>Request Details</h2>
  <form action = "{% url 'core:submit' RequestID %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>     <button onclick="DeleteButton()" type="button">Delete Request</button>
  </form>

<script>
function DeleteButton(){
  if (confirm("Confirm deleting game request?") == true){
    window.location = '{% url 'core:delete' RequestID %}'
    }
  }
</script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <p style="text-align:left;">
        D&D Player Finder 0.1
        <span style="float:right;">
           Hi {{ user.username }}!   |   <a href="{% url 'logout' %}">Log Out</a>
        </span>
    </p>
    <hr>

    {% if GameRequestList %}
    <ul>
        {% for GameRequest in GameRequestList %}
            <li><a href="{% url 'core:details' GameRequest.id %}">{{ GameRequest.request_name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>You do not have any active game requests yet.</p>
    {% endif %}
    <a href="{% url 'core:new request' %}">Create new request.</a>

{% else %}
<p style="text-align:left;">
    D&D Player Finder 0.1
    <span style="float:right;">
       <a href="{% url 'login' %}">Log in</a> or <a href="{% url 'signup' %}">sign up.</a>
    </span>
</p>
<hr>
You must be logged in to view or submit game requests.
{% endif %}
{% endblock %}